// <auto-generated />
using System;
using LogisticaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticaBackend.Migrations
{
    [DbContext(typeof(LogisticaContext))]
    [Migration("20251128014111_EliminaFacturasMovimientos")]
    partial class EliminaFacturasMovimientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionLogisticaBackend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cliente");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Conductor", b =>
                {
                    b.Property<int>("IdConductor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_conductor");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdConductor"));

                    b.Property<string>("ClaseLicencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("clase_licencia");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("conductor");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("VencimientoLicencia")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vencimiento_licencia");

                    b.HasKey("IdConductor");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("conductores");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Envio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_envio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEnvio"));

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_total");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado_envio");

                    b.Property<DateTime>("FechaCreacionEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion_envio");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_salida");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdConductor")
                        .HasColumnType("int")
                        .HasColumnName("id_conductor");

                    b.Property<int>("IdDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_destino");

                    b.Property<int>("IdOrigen")
                        .HasColumnType("int")
                        .HasColumnName("id_origen");

                    b.Property<int>("IdTipoCarga")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_carga");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("NumeroSeguimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_seguimiento");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("VolumenM3")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volumen_m3");

                    b.HasKey("IdEnvio");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdConductor");

                    b.HasIndex("IdDestino");

                    b.HasIndex("IdOrigen");

                    b.HasIndex("IdTipoCarga");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("envios");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_localidad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLocalidad"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("localidad");

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("localidades");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("CodigoIso")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("codigo_iso");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pais");

                    b.HasKey("IdPais");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("paises");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_provincia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provincia");

                    b.HasKey("IdProvincia");

                    b.HasIndex("IdPais");

                    b.ToTable("provincias");
                });

            modelBuilder.Entity("LogisticaBackend.Models.TipoCarga", b =>
                {
                    b.Property<int>("IdTipoCarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_carga");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoCarga"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("carga");

                    b.HasKey("IdTipoCarga");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipos_carga");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_localidad");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("IdLocalidad");

                    b.ToTable("ubicaciones");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<decimal>("CapacidadKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacidad_kg");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("patente");

                    b.Property<DateTime>("RtoVencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rto_vencimiento");

                    b.Property<DateTime>("UltimaInspeccion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultima_inspeccion");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("vehiculos");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Envio", b =>
                {
                    b.HasOne("LogisticaBackend.Models.Cliente", "Cliente")
                        .WithMany("Envios")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBackend.Models.Conductor", "Conductor")
                        .WithMany("Envios")
                        .HasForeignKey("IdConductor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBackend.Models.Ubicacion", "Destino")
                        .WithMany("EnviosDestino")
                        .HasForeignKey("IdDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBackend.Models.Ubicacion", "Origen")
                        .WithMany("EnviosOrigen")
                        .HasForeignKey("IdOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticaBackend.Models.TipoCarga", "TipoCarga")
                        .WithMany("Envios")
                        .HasForeignKey("IdTipoCarga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticaBackend.Models.Vehiculo", "Vehiculo")
                        .WithMany("Envios")
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");

                    b.Navigation("Destino");

                    b.Navigation("Origen");

                    b.Navigation("TipoCarga");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Localidad", b =>
                {
                    b.HasOne("LogisticaBackend.Models.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Provincia", b =>
                {
                    b.HasOne("LogisticaBackend.Models.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Ubicacion", b =>
                {
                    b.HasOne("LogisticaBackend.Models.Localidad", "Localidad")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("IdLocalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localidad");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Cliente", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Conductor", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Localidad", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("LogisticaBackend.Models.TipoCarga", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Ubicacion", b =>
                {
                    b.Navigation("EnviosDestino");

                    b.Navigation("EnviosOrigen");
                });

            modelBuilder.Entity("LogisticaBackend.Models.Vehiculo", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
